ALTER TABLE public.captures
  ADD COLUMN capture_no bigint GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public.captures
  ADD CONSTRAINT captures_capture_no_key UNIQUE (capture_no);

COMMENT ON COLUMN public.captures.capture_no IS
  'Human-facing capture number used in receipts and /fix, /flag. Global
   identity, not per-owner: a per-owner counter would serialise ~30
   concurrent /batch inserts on one row lock.';
